 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/session_attendances", type: :request do
  # SessionAttendance. As you add validations to SessionAttendance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SessionAttendance.create! valid_attributes
      get session_attendances_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      session_attendance = SessionAttendance.create! valid_attributes
      get session_attendance_url(session_attendance)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_session_attendance_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      session_attendance = SessionAttendance.create! valid_attributes
      get edit_session_attendance_url(session_attendance)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SessionAttendance" do
        expect {
          post session_attendances_url, params: { session_attendance: valid_attributes }
        }.to change(SessionAttendance, :count).by(1)
      end

      it "redirects to the created session_attendance" do
        post session_attendances_url, params: { session_attendance: valid_attributes }
        expect(response).to redirect_to(session_attendance_url(SessionAttendance.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SessionAttendance" do
        expect {
          post session_attendances_url, params: { session_attendance: invalid_attributes }
        }.to change(SessionAttendance, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post session_attendances_url, params: { session_attendance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested session_attendance" do
        session_attendance = SessionAttendance.create! valid_attributes
        patch session_attendance_url(session_attendance), params: { session_attendance: new_attributes }
        session_attendance.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the session_attendance" do
        session_attendance = SessionAttendance.create! valid_attributes
        patch session_attendance_url(session_attendance), params: { session_attendance: new_attributes }
        session_attendance.reload
        expect(response).to redirect_to(session_attendance_url(session_attendance))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        session_attendance = SessionAttendance.create! valid_attributes
        patch session_attendance_url(session_attendance), params: { session_attendance: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested session_attendance" do
      session_attendance = SessionAttendance.create! valid_attributes
      expect {
        delete session_attendance_url(session_attendance)
      }.to change(SessionAttendance, :count).by(-1)
    end

    it "redirects to the session_attendances list" do
      session_attendance = SessionAttendance.create! valid_attributes
      delete session_attendance_url(session_attendance)
      expect(response).to redirect_to(session_attendances_url)
    end
  end
end
