 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/timetabled_sessions", type: :request do
  # TimetabledSession. As you add validations to TimetabledSession, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TimetabledSession.create! valid_attributes
      get timetabled_sessions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      timetabled_session = TimetabledSession.create! valid_attributes
      get timetabled_session_url(timetabled_session)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_timetabled_session_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      timetabled_session = TimetabledSession.create! valid_attributes
      get edit_timetabled_session_url(timetabled_session)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TimetabledSession" do
        expect {
          post timetabled_sessions_url, params: { timetabled_session: valid_attributes }
        }.to change(TimetabledSession, :count).by(1)
      end

      it "redirects to the created timetabled_session" do
        post timetabled_sessions_url, params: { timetabled_session: valid_attributes }
        expect(response).to redirect_to(timetabled_session_url(TimetabledSession.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TimetabledSession" do
        expect {
          post timetabled_sessions_url, params: { timetabled_session: invalid_attributes }
        }.to change(TimetabledSession, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post timetabled_sessions_url, params: { timetabled_session: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested timetabled_session" do
        timetabled_session = TimetabledSession.create! valid_attributes
        patch timetabled_session_url(timetabled_session), params: { timetabled_session: new_attributes }
        timetabled_session.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the timetabled_session" do
        timetabled_session = TimetabledSession.create! valid_attributes
        patch timetabled_session_url(timetabled_session), params: { timetabled_session: new_attributes }
        timetabled_session.reload
        expect(response).to redirect_to(timetabled_session_url(timetabled_session))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        timetabled_session = TimetabledSession.create! valid_attributes
        patch timetabled_session_url(timetabled_session), params: { timetabled_session: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested timetabled_session" do
      timetabled_session = TimetabledSession.create! valid_attributes
      expect {
        delete timetabled_session_url(timetabled_session)
      }.to change(TimetabledSession, :count).by(-1)
    end

    it "redirects to the timetabled_sessions list" do
      timetabled_session = TimetabledSession.create! valid_attributes
      delete timetabled_session_url(timetabled_session)
      expect(response).to redirect_to(timetabled_sessions_url)
    end
  end
end
